# Generated by Django 3.1.2 on 2020-10-17 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='cr_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.restaurants'),
        ),
    ]
