# Generated by Django 3.1.2 on 2020-10-17 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201017_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='cr_at',
        ),
        migrations.AddField(
            model_name='foods',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
