# Generated by Django 3.1.2 on 2020-10-17 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_foods_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
