# Generated by Django 3.1.2 on 2020-10-17 17:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20201017_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='foods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
